# Generated by Django 2.0.7 on 2018-07-26 22:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('freebet', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('signup', 'signup'), ('deposit', 'deposit'), ('initial', 'initial'), ('free', 'free'), ('complete', 'complete')], default='signup', max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('banked', models.BooleanField(default=False)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Summaries',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.Summary'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('affiliate', 'summary')},
        ),
    ]
