# Generated by Django 2.0.7 on 2018-07-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='username',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
