# Generated by Django 2.0.7 on 2018-08-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='slug',
            field=models.SlugField(),
        ),
    ]
