# Generated by Django 2.0.7 on 2018-08-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20180801_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
