# Generated by Django 2.0.7 on 2018-07-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20180718_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='banked',
            field=models.BooleanField(default=False),
        ),
    ]
