# Generated by Django 2.0.7 on 2018-08-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180810_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='one_line',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
